### ISSUE TITLE
Guardian Roll - Display routine not going back to the top of the stack

### ISSUE THREAD

**Issue by jeremyfuksa** [jeremyfuksa/blue-elk-kiosks#11]
Once the roll hits the end of the JSON data, Razzle renders an error: `TypeError: Cannot read property 'guardianName' of undefined`.

Seems like the `fetchFifty()` function isn't properly going back to the top of the data array once the end is hit.

React stack trace points to https://github.com/jeremyfuksa/blue-elk-kiosks/blob/41e11884b592075a5663be0db82883b27448851e/src/routes/roll/Roll.jsx#L38 as the culprit. But, that seems fine to me. @mraplumb, do you happen to see what's up?

**Comment by mraplumb** [comment]
@jeremyfuksa 

I wasn't sure what the steps were to build and run the project locally so I didn't actually run through the app to see the error.  After reading through the code, my first thought of what might be wrong is with line 41.  Seems like `counter` in the line below should actually be `tempCounter`
```javascript
  if (counter === numRecords - 1) {
```

Once the `for` loop reaches the max `numRecords`, `counter` isn't set to that value until after this `if` statement.  Seems like that would cause the `for loop` to execute one more time against records that aren't actually there.

I wasn't sure what the steps were to build and run the project locally so I didn't actually run through the app to see the error.

**Comment by jeremyfuksa** [comment]
Fixed.
